
// Auto generated by typewriter from c# code. Update coresponding c# code to re-generate this file.
import {HttpClientAPI} from '../provider/httpClient';

import {LoginResponse} from '../model/view/loginResponse';
import {LoginRequest} from '../model/view/loginRequest';

import { Right } from '../model/enums';


export function login(api: HttpClientAPI,request: LoginRequest) {
  return api.http<LoginResponse>(`/api/auth`, { method: 'post' , body: JSON.stringify(request) });
}
