
// Auto generated by typewriter from c# code. Update coresponding c# code to re-generate this file.
import {ApiResponse} from '../model/view/apiResponse';
import {HttpClientAPI} from '../provider/httpClient';




export function userImage(id: number) {
  return `/api/user/userImage${id}`;
}
export function userThumb(id: number) {
  return `/api/user/userThumb${id}`;
}

