
// Auto generated by typewriter from c# code. Update coresponding c# code to re-generate this file.
import {ApiResponse} from '../model/view/apiResponse';
import {HttpClientAPI} from '../provider/httpClient';

import {ProfileUpdateRequest} from '../model/view/profileUpdateRequest';



export function userImage(id: number) {
  return `/api/user/userImage${id}`;
}
export function userThumb(id: number) {
  return `/api/user/userThumb${id}`;
}

export function updateProfile(api: HttpClientAPI,request: ProfileUpdateRequest) {
  return api.http<ApiResponse<ProfileUpdateRequest>>(`/api/user/updateProfile`, { method: 'post' , body: JSON.stringify(request) });
}

